[package]
name = "kf"
version = "0.1.0"
authors = ["jgroene <jannik.groene@gmail.com>"]
edition = "2024"
build="src/build.rs"

[lib]
name = "kf_internals"
bench = true

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.test]
opt-level = 3
lto = "fat"
codegen-units = 1

[profile.bench]
opt-level = 3
debug = true

[dependencies]
rand = "0.8.4"
arrayvec = { version = "0.7.2" }

[build-dependencies]
rand = { version = "0.8.4", features = ["small_rng"] }

[dev-dependencies]
criterion = "0.3"
criterion-cycles-per-byte = "0.1.2"

[[bench]]
name = "move_gen_bench"
harness = false
