[package]
name = "kf"
version = "0.0.8"
authors = ["jgroene <jannik.groene@gmail.com>"]
edition = "2021"
build="src/build.rs"

[lib]
name = "kf_internals"
bench = true

[profile.dev]
opt-level = 3

[profile.release]
debug = true
opt-level = 3
lto = true
codegen-units = 1

[profile.test]
opt-level = 3

[profile.bench]
opt-level = 3
debug = true

[dependencies]
rand = "0.8.4"
arrayvec = { version = "0.7.2" }
lazy_static = "1.4.0"
nnue = {path="../nnue"}
parking_lot = { version = "0.12.5" }

[build-dependencies]
rand = { version = "0.8.4", features = ["small_rng"] }

[dev-dependencies]
criterion = "0.3"
criterion-cycles-per-byte = "0.1.2"

[[bench]]
name = "move_gen_bench"
harness = false
